apiVersion: v1
kind: Namespace
metadata:
  name: astro-portfolio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: astro-portfolio
spec:
  selector:
    matchLabels:
      app: astro-portfolio
  replicas: 1
  template:
    metadata:
      labels:
        app: astro-portfolio
    spec:
      containers:
        - name: astro-portfolio
          image: registry.gitlab.com/jacobmbanghart/astro-portfolio:0.0.5 # {"$imagepolicy": "flux-system:portfolio"}
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
            requests:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: astro-portfolio
spec:
  selector:
    app: astro-portfolio
  type: ClusterIP
  ports:
    - port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: astro-portfolio
  labels:
    name: astro-portfolio
spec:
  rules:
    - host: jacobbanghart.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: astro-portfolio
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: astro-portfolio-www
  labels:
    name: astro-portfolio-www
spec:
  rules:
    - host: www.jacobbanghart.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: astro-portfolio
                port:
                  number: 8080
