resources:
  - ../../application
  - ./domains.yaml
nameSuffix: -prod
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: notImportantHere
      namespace: portfolio-prod
    unsetOnly: true