apiVersion: v1
kind: Namespace
metadata:
  name: astro-portfolio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: astro-portfolio
  namespace: astro-portfolio
spec:
  selector:
    matchLabels:
      app: astro-portfolio
  replicas: 2
  template:
    metadata:
      labels:
        app: astro-portfolio
    spec:
      containers:
        - name: astro-portfolio
          image: registry.gitlab.com/jacobmbanghart/astro-portfolio:0.0.10 # {"$imagepolicy": "flux-system:portfolio"}
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
            requests:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: astro-portfolio
  namespace: astro-portfolio
spec:
  selector:
    app: astro-portfolio
  type: ClusterIP
  ports:
    - port: 8080